# ./docker-compose.yml

version: '3'

services:
  db:
    container: api-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9907:3306"
  api:
    image: php:7.2.2-apache
    container_name: api
    depends_on:
      - db
    volumes:
      - ./api/:/var/www/html/
    ports:
      - "8101:80"
    stdin_open: true
    tty: true